#Description:
#  本地代价地图需要配置的参数，各参数意义如下:
#  global_frame:在本地代价地图中的全局坐标系;
#  robot_base_frame:机器人本体的基坐标系;

local_costmap:
  global_frame: map #odom避免 AMCL 对 map->odom 的小幅校正直接抖动局部地图。
  robot_base_frame: base_link
  update_frequency: 20.0
  publish_frequency: 5.0
  static_map: true
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.03
  transform_tolerance: 10
  # footprint_padding: 0.02
  plugins:
#    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


  obstacle_layer:
      enabled: true
      combination_method: 1
      track_unknown_space: true

      obstacle_range: 1.5
      raytrace_range: 2.0
      observation_sources: laser_scan_sensor

      laser_scan_sensor:
        sensor_frame: laser_frame
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true
        inf_is_valid: true